apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-configuration
  labels:
    k8s-app: nginx-ingress-controller
  namespace: kube-system
data:
  proxy-connect-timeout: "10"
  proxy-read-timeout: "120"
  proxy-send-timeout: "120"
